=== rosetta-models/demo/rosetta-source/src/main/resources/schemas/external-synonym/example-7.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="dataDocument">
        <xs:complexType>
            <xs:all>
                <xs:element name="engineType">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="engineDetail">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="specificationRef" type="SpecificationReference"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="specifications" type="Specifications"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="true" name="Reference">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                The abstract base class for all types which define intra-document pointers.
            </xs:documentation>
        </xs:annotation>
    </xs:complexType>

    <xs:complexType name="SpecificationReference">
        <xs:annotation>
            <xs:documentation xml:lang="en">Reference to C</xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="Reference">
                <xs:attribute name="href" type="xs:IDREF" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Specifications">
        <xs:sequence>
            <xs:element name="powerUnit"/>
            <xs:element name="cylinders"/>
            <xs:element name="combustible" type="FuelEnum"/>
            <xs:element name="manufacturer"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:simpleType name="FuelEnum">
        <xs:restriction base="xs:token">
            <xs:enumeration value="Diesel">
            </xs:enumeration>
            <xs:enumeration value="Gasoline">
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== rosetta-models/demo/rosetta-source/src/main/resources/cdm-sample-files/external-synonym/example-7/example-7-1.xml
<?xml version="1.0"?>
<dataDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="example-7.xsd example-7.xsd">
    <engineType>
        <engineDetail>
            <specificationRef href="xyz"/>
        </engineDetail>
        <specifications id="xyz">
            <powerUnit>HP</powerUnit>
            <cylinders>3</cylinders>
            <combustible>Gasoline</combustible>
            <manufacturer>ford</manufacturer>
        </specifications>
    </engineType>
</dataDocument>
